x-template: &flyway-template
  image: flyway/flyway:10
  volumes:
    - ./db/migrations:/flyway/migrations
    - ./db/flyway.conf:/flyway/flyway.conf
  depends_on:
    - db
  networks:
    - fusen-network

services:
  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

  flyway-repair:
    <<: *flyway-template
    command: repair
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "fusen_local"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - fusen-network
    command: --default-authentication-plugin=mysql_native_password

  fusen-api:
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fusen_local?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - fusen-network

networks:
  fusen-network:
    driver: bridge
